name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      uses: borales/actions-yarn@v5
      with:
        cmd: install --immutable

    - name: Prepare
      uses: borales/actions-yarn@v5
      with:
        cmd: prepare

    - name: Pack
      uses: borales/actions-yarn@v5
      with:
        cmd: pack

  docs:
    name: Docs
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Build docs
      uses: borales/actions-yarn@v5
      with:
        cmd: docs
